#!/bin/bash
#
# All Files for /usr/local/bin should be declare here for global use
# Copyright 2022 bombi

function loadSystem() {

  if [[ "$(which git)"  == "" ]];
  then
    echo "git is not installed"
    echo "install git"
    sudo apt install -y git || exit 0
  else
    echo "git is installed"
  fi

  git init

  git config config.user "Partarum"
  git config config.email "email@partarum.de"

  git remote rm origin

  git remote add origin "$1"

  git config --global --add --bool push.autoSetupRemote true

  git fetch

  git checkout -b main

  git pull -f origin main

  git checkout -b partarum

  git remote rm origin

  git remote add origin https://github.com/partarum/partarum.git

  git fetch

  git pull -f origin main

  git checkout main

  git merge partarum

  git remote rm origin

  git remote add origin "$1"

  git commit -a -m "add Partarum"

  git push

  git status > status.txt
}

function main() {

  loadSystem "$@"
}

main "$@"