#!/bin/bash
#
# All Files for /usr/local/bin should be declare here for global use
# Copyright 2022 bombi

function loadSystem() {

  if [[ "$(which git)"  == "" ]];
  then
    echo "git is not installed"
    echo "install git"
    sudo apt install -y git || exit 0
  else
    echo "git is installed"
  fi

  mkdir -p log/initPartarum

  git status &> log/initPartarum/statusStart.txt

  # test ob Ordner schon initialisiert ist

  # test ob in einem Git - Projekt
  # inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"

  # test ob in einem Git - Initialisierten Ordner
  # is_git_init="$(git rev-parse --git-dir 2>/dev/null)"
  # wenn in einem Git - Initialisierten Folder drinn, dann ist das Ergebniss ".git"
  # [[ $is_git_init == ".git" ]] && echo "Initialisierter Folder"
  # wenn in einem Folder von einem Git - Initialisierten Folder drinn, dann ist das Ergebniss "/path/.git"
  # wenn keine Initialisierung vorliegt, dann kommt ein leerer String
  # [[ $is_git_init == "" ]] && echo "Nicht initialisiert"


  [[ $is_git_init != ".git" ]] && git init

  git config config.user "Partarum"
  git config config.email "email@partarum.de"

  git remote rm origin

  git remote add origin "$1"

  [[ $(git config --get push.autoSetupRemote) != true ]] && git config --global --add --bool push.autoSetupRemote true

  git fetch &> log/initPartarum/fetchRemote.txt

  git checkout -b main

  git pull origin main --allow-unrelated-histories &> log/initPartarum/pullUserRep.txt

  git checkout -b partarum

  git remote rm origin

  git remote add origin https://github.com/partarum/dev.partarum.download.git

  git fetch &> log/initPartarum/fetchPartarum.txt

  git pull origin main --allow-unrelated-histories &> log/initPartarum/pullPartarum.txt

  ls &> log/initPartarum/folderAfterPullPartarum.txt

  git checkout main

  git merge partarum &> log/initPartarum/mergePartarum.txt

  git remote rm origin

  git remote add origin "$1"

  git commit -a -m "add Partarum"

  git push

  git status &> log/initPartarum/status.txt
}

function main() {

  loadSystem "$@"
}

main "$@"